version: '3.7'
services:
  db:
    container_name: "crud-api"
    platform: windows/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: " secret"
      MYSQL_DATABSE: "tasks"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "secret"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "crud_api"
    build: 
      context: .
      dockerfile: api.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
    - .:/src/go-workspace/crud-api/
